package kr.yuhan.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class YuhanMessageVO 
{
	private int YUHAN_MESSAGE_NUMBER;
	private String YUHAN_MESSAGE_FROM_MEMBER_NUMBER;
	private String YUHAN_MESSAGE_TO_MEMBER_NUMBER;
	private String YUHAN_MESSAGE_SUBJECT;
	private String YUHAN_MESSAGE_CONTENT;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+9")
	private Date YUHAN_MESSAGE_SEND_DATE;
	private String YUHAN_MESSAGE_READ_STATUS;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+9")
	private Date YUHAN_MESSAGE_READ_DATE;
	private String YUHAN_MESSAGE_STATUS;
	private String SENDDATE;
	
	public String getSENDDATE() {
		return SENDDATE;
	}

	public void setSENDDATE(String sENDDATE) {
		SENDDATE = sENDDATE;
	}

	public int getYUHAN_MESSAGE_NUMBER() 
	{
		return YUHAN_MESSAGE_NUMBER;
	}
	
	public void setYUHAN_MESSAGE_NUMBER(int yUHAN_MESSAGE_NUMBER) 
	{
		YUHAN_MESSAGE_NUMBER = yUHAN_MESSAGE_NUMBER;
	}
	
	public String getYUHAN_MESSAGE_FROM_MEMBER_NUMBER() 
	{
		return YUHAN_MESSAGE_FROM_MEMBER_NUMBER;
	}

	public void setYUHAN_MESSAGE_FROM_MEMBER_NUMBER(String yUHAN_MESSAGE_FROM_MEMBER_NUMBER) 
	{
		YUHAN_MESSAGE_FROM_MEMBER_NUMBER = yUHAN_MESSAGE_FROM_MEMBER_NUMBER;
	}
	
	public String getYUHAN_MESSAGE_TO_MEMBER_NUMBER() 
	{
		return YUHAN_MESSAGE_TO_MEMBER_NUMBER;
	}
	
	public void setYUHAN_MESSAGE_TO_MEMBER_NUMBER(String yUHAN_MESSAGE_TO_MEMBER_NUMBER) 
	{
		YUHAN_MESSAGE_TO_MEMBER_NUMBER = yUHAN_MESSAGE_TO_MEMBER_NUMBER;
	}
	
	public String getYUHAN_MESSAGE_SUBJECT() 
	{
		return YUHAN_MESSAGE_SUBJECT;
	}
	
	public void setYUHAN_MESSAGE_SUBJECT(String yUHAN_MESSAGE_SUBJECT) 
	{
		YUHAN_MESSAGE_SUBJECT = yUHAN_MESSAGE_SUBJECT;
	}
	
	public String getYUHAN_MESSAGE_CONTENT() 
	{
		return YUHAN_MESSAGE_CONTENT;
	}
	
	public void setYUHAN_MESSAGE_CONTENT(String yUHAN_MESSAGE_CONTENT) 
	{
		YUHAN_MESSAGE_CONTENT = yUHAN_MESSAGE_CONTENT;
	}
	
	public Date getYUHAN_MESSAGE_SEND_DATE() 
	{
		return YUHAN_MESSAGE_SEND_DATE;
	}
	
	public void setYUHAN_MESSAGE_SEND_DATE(Date yUHAN_MESSAGE_SEND_DATE) 
	{
		YUHAN_MESSAGE_SEND_DATE = yUHAN_MESSAGE_SEND_DATE;
	}
	
	public String getYUHAN_MESSAGE_READ_STATUS() 
	{
		return YUHAN_MESSAGE_READ_STATUS;
	}
	
	public void setYUHAN_MESSAGE_READ_STATUS(String yUHAN_MESSAGE_READ_STATUS) 
	{
		YUHAN_MESSAGE_READ_STATUS = yUHAN_MESSAGE_READ_STATUS;
	}
	
	public Date getYUHAN_MESSAGE_READ_DATE() 
	{
		return YUHAN_MESSAGE_READ_DATE;
	}
	
	public void setYUHAN_MESSAGE_READ_DATE(Date yUHAN_MESSAGE_READ_DATE) 
	{
		YUHAN_MESSAGE_READ_DATE = yUHAN_MESSAGE_READ_DATE;
	}
	
	public String getYUHAN_MESSAGE_STATUS() 
	{
		return YUHAN_MESSAGE_STATUS;
	}
	
	public void setYUHAN_MESSAGE_STATUS(String yUHAN_MESSAGE_STATUS)
	{
		YUHAN_MESSAGE_STATUS = yUHAN_MESSAGE_STATUS;
	}

	@Override
	public String toString() 
	{
		return "YuhanMessageVO [YUHAN_MESSAGE_NUMBER=" + YUHAN_MESSAGE_NUMBER + ", YUHAN_MESSAGE_FROM_MEMBER_NAME="
				+ YUHAN_MESSAGE_FROM_MEMBER_NUMBER + ", YUHAN_MESSAGE_TO_MEMBER_NAME=" + YUHAN_MESSAGE_TO_MEMBER_NUMBER
				+ ", YUHAN_MESSAGE_SUBJECT=" + YUHAN_MESSAGE_SUBJECT + ", YUHAN_MESSAGE_CONTENT="
				+ YUHAN_MESSAGE_CONTENT + ", YUHAN_MESSAGE_SEND_DATE=" + YUHAN_MESSAGE_SEND_DATE
				+ ", YUHAN_MESSAGE_READ_STATUS=" + YUHAN_MESSAGE_READ_STATUS + ", YUHAN_MESSAGE_READ_DATE="
				+ YUHAN_MESSAGE_READ_DATE + ", YUHAN_MESSAGE_STATUS=" + YUHAN_MESSAGE_STATUS + "]";
	}
}
